# EDCOP Moloch Chart values
images:
  moloch: gcr.io/edcop-dev/mike-moloch:5
  runner: gcr.io/edcop-public/runner:8
networks:
  # Overlay is the name of the default cni network
  overlay: calico
  # Passive is the name of the SR-IOV network - ignore if using host networking
  passive: passive
  # true/false. Directly exposes host interfaces to the container instead of using SR-IOV.
  # See github.com/sealingtech/EDCOP-CONFIGURESENSORS for more information
  useHostNeworking: false
volumes:
  # Persistent data location on the host to store Moloch's data
  raw: /EDCOP/bulk/moloch/raw
nodeSelector:
  worker: sensor
  viewer: infrastructure
ingress:
  # Enter the FQDN of your host
  host: moloch.physical.edcop.io
molochConfig:  
  # Worker nodes refers to the number of worker nodes you have
  workerNodes: 1
  # These settings impact Moloch's overall performance
  # https://github.com/aol/moloch/wiki/Settings#High_Performance_Settings
  performance:
    maxStreams: 1000000
    maxPacketsInQueue: 200000
    maxPackets: 10000           # Moloch writes a session record after this many
    packetThreads: 1            
    pcapWriteSize: 262144       # Buffer size when writing pcap files
    tpacketv3Threads: 2         
  env:
    # Admin user for the web interface
    adminpw: supersecretpw
    clusterpw: anothersupersecretpw
    encryptpw: randencryptpw    # Recommanded to be random, never have to type it in
  # Requests are set to accommodate limited resource VMs
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 4 
    memory: 8G
